name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: '3.8', python: '3.8', tox: py38}
          - {name: '3.7', python: '3.7', tox: py37}
          - {name: 'format', python: '3.10', tox: format}
          - {name: 'mypy', python: '3.10', tox: mypy}
          - {name: 'pep8', python: '3.10', tox: pep8}
          - {name: 'package', python: '3.10', tox: package}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox

      - run: tox -e ${{ matrix.tox }}


  h2spec:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'asyncio', worker: 'asyncio'}
          - {name: 'trio', worker: 'trio'}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install trio .

      - name: Run server
        working-directory: compliance/h2spec
        run: nohup hypercorn --keyfile key.pem --certfile cert.pem -k ${{ matrix.worker }} server:app &

      - name: Download h2spec
        run: |
          wget https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz
          tar -xvf h2spec_linux_amd64.tar.gz

      - name: Run h2spec
        run: ./h2spec -tk -h 127.0.0.1 -p 8000 -o 10

  autobahn:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container: python:2.7.16-alpine3.10
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'asyncio', worker: 'asyncio'}
          - {name: 'trio', worker: 'trio'}

    steps:
      - uses: actions/checkout@v3

      - run: apk --update add build-base libressl libressl-dev ca-certificates libffi-dev python3 python3-dev

      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install pyopenssl==19.1.0 cryptography==2.3.1 Twisted==12.1 wsaccel==0.6.2 autobahntestsuite
      - run: python3 -m pip install trio .

      - name: Run server
        working-directory: compliance/autobahn
        run: nohup hypercorn -k ${{ matrix.worker }} server:app &

      - name: Run server
        working-directory: compliance/autobahn
        run: wstest -m fuzzingclient && python summarise.py
